services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: skillet
      POSTGRES_PASSWORD: skillet
      POSTGRES_DB: skilletfresh
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
